-- INSERT PARA LA DIM_PACIENTE
SELECT 
    P.ID_PACIENTE, P.NOMBRE, P.SEXO, P.FECHA_NACIMIENTO, P.EDAD, 
    P.TELEFONO, P.EMAIL, P.DIRECCION,
    D.NOMBRE AS DEPARTAMENTO, M.NOMBRE AS MUNICIPIO, D.NOMBRE AS DISTRITO
FROM TRX_PACIENTES P INNER JOIN DISTRITOS D
ON P.ID_DISTRITO=D.ID_DISTRITO INNER JOIN MUNICIPIOS M
ON D.ID_MUNICIPIO=M.ID_MUNICIPIO INNER JOIN DEPARTAMENTOS DP
ON M.ID_DEPARTAMENTO=DP.ID_DEPARTAMENTO;

-- INSERT PARA LA DIM_MEDICO
SELECT 
    M.ID_MEDICO,
    M.NOMBRE, M.NUMERO_REGISTRO, M.DIRECCION, M.TELEFONO, M.EMAIL, E.NOMBRE AS ESPECIALIDAD
FROM TRX_MEDICOS M INNER JOIN TRX_MEDICO_ESPECIALIDADES ME
ON M.ID_MEDICO=ME.ID_MEDICO INNER JOIN TRX_ESPECIALIDADES E
ON ME.ID_ESPECIALIDAD=E.ID_ESPECIALIDAD;

-- INSERT PARA LA DIM_UNIDADES
SELECT 
    ID_UNIDAD,
    U.NOMBRE, 
    DIRECCION, 
    D.NOMBRE AS DISTRITO,
    U.TIPO
FROM TRX_UNIDADES U INNER JOIN DISTRITOS D
ON U.ID_DISTRITO=D.ID_DISTRITO;

-- INSERT PARA LA DIM_ASEGURADORAS
SELECT
    ID_ASEGURADORA,
    NOMBRE, CONTACTO, TELEFONO, EMAIL, DIRECCION
FROM ASEGURADORAS;

-- INSERT PARA LA DIM_SERVICIOS
SELECT
    S.ID_SERVICIO,
    S.CODIGO_ESTANDAR,
    S.DESCRIPCION,
    TS.NOMBRE AS TIPO_SERVICIO,
    E.NOMBRE AS ESPECIALIDAD,
    S.PRECIO_UNITARIO
FROM TRX_SERVICIOS S INNER JOIN TRX_TIPOS_SERVICIOS TS
ON S.ID_TIPO_SERVICIO=TS.ID_TIPO_SERVICIO INNER JOIN TRX_ESPECIALIDADES E
ON S.ID_ESPECIALIDAD=E.ID_ESPECIALIDAD;

-- INSERT PARA LA DIM_SEGUROS
SELECT 
    S.ID_SEGURO,
    S.PLAN,
    A.NOMBRE AS ASEGURADORA
FROM TRX_SEGUROS S INNER JOIN ASEGURADORAS A
ON S.ID_ASEGURADORA=A.ID_ASEGURADORA;

-- INSERT PARA LA DIM_TIEMPO
SELECT 
    TO_NUMBER(TO_CHAR(TRUNC(fecha), 'YYYYMMDD')) AS id_tiempo,
    TRUNC(fecha) AS fecha,
    EXTRACT(MONTH FROM fecha) AS mes,
    TO_NUMBER(TO_CHAR(fecha, 'Q')) AS trimestre,
    EXTRACT(YEAR FROM fecha) AS anio
FROM trx_atenciones
GROUP BY TRUNC(fecha), EXTRACT(MONTH FROM fecha), TO_CHAR(fecha, 'Q'), EXTRACT(YEAR FROM fecha)
ORDER BY TRUNC(fecha);

--INSERT PARA LA DIM_DIAGNOSTICOS
SELECT
    ID_DIAGNOSTICO,
    CODIGO AS CODIGO_DIAGNOSTICO,
    DESCRIPCION
FROM CIE10_DIAGNOSTICOS;

-- INSER PARA LA DIM_TIPO_URGENCIA
SELECT 
    ID_TIPO_URGENCIA,
    NOMBRE,
    DESCRIPCION,
    NIVEL_PRIORIDAD
FROM TRX_TIPO_URGENCIA;

-- INSERT PARA FACT_CONSULTAS_MEDICAS
SELECT 
    A.ID_ATENCION,
    A.ID_PACIENTE,
    D.ID_MEDICO,
    A.ID_UNIDAD,
    D.ID_SERVICIO,
    D.ID_SEGURO,
    TO_NUMBER(TO_CHAR(TRUNC(A.FECHA), 'YYYYMMDD')) AS ID_TIEMPO,
    AD.ID_DIAGNOSTICO,
    TU.ID_TIPO_URGENCIA,
    D.COBERTURA,
    D.PRECIO_UNITARIO
FROM TRX_ATENCIONES A INNER JOIN TRX_DETALLE D
ON A.ID_ATENCION=D.ID_ATENCION INNER JOIN ATENCION_DIAGNOSTICOS AD
ON A.ID_ATENCION=AD.ID_ATENCION INNER JOIN TRX_TIPO_URGENCIA TU
ON A.ID_TIPO_URGENCIA=TU.ID_TIPO_URGENCIA
ORDER BY A.ID_ATENCION;