/*
* CREANDO ESTRUCTURA OLAP
*/
CREATE TABLE dim_paciente(
    id_paciente NUMBER NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    sexo CHAR(1),
    fecha_nacimiento DATE NOT NULL,
    edad INT NOT NULL,
    telefono VARCHAR2(15),
    email VARCHAR2(2),
    direccion VARCHAR2(200),
    departamento  VARCHAR2(50),
    municipio  VARCHAR2(50),
    distrito  VARCHAR2(50)
);

-- INSERT DE DATOS
SELECT 
    P.ID_PACIENTE, P.NOMBRE, P.SEXO, P.FECHA_NACIMIENTO, P.EDAD, 
    P.TELEFONO, P.EMAIL, P.DIRECCION,
    D.NOMBRE AS DEPARTAMENTO, M.NOMBRE AS MUNICIPIO, D.NOMBRE AS DISTRITO
FROM TRX_PACIENTES P INNER JOIN DISTRITOS D
ON P.ID_DISTRITO=D.ID_DISTRITO INNER JOIN MUNICIPIOS M
ON D.ID_MUNICIPIO=M.ID_MUNICIPIO INNER JOIN DEPARTAMENTOS DP
ON M.ID_DEPARTAMENTO=DP.ID_DEPARTAMENTO;


CREATE TABLE dim_medico (
    id_medico NUMBER,
    nombre VARCHAR2(100),
    numero_registro VARCHAR2,
    direccion VARCHAR2(200),
    telefono VARCHAR2(15),
    email VARCHAR2(100),
    especialidad VARCHAR2(100)
);

-- INSERT DE DATOS
SELECT 
    M.ID_MEDICO,
    M.NOMBRE, M.NUMERO_REGISTRO, M.DIRECCION, M.TELEFONO, M.EMAIL, E.NOMBRE AS ESPECIALIDAD
FROM TRX_MEDICOS M INNER JOIN TRX_MEDICO_ESPECIALIDADES ME
ON M.ID_MEDICO=ME.ID_MEDICO INNER JOIN TRX_ESPECIALIDADES E
ON ME.ID_ESPECIALIDAD=E.ID_ESPECIALIDAD;

CREATE TABLE dim_unidades (
    id_unidad NUMBER,
    nombre VARCHAR2(100),
    direccion VARCHAR2(200),
    distrito VARCHAR2(50),
    tipo VARCHAR2(50)
);

-- INSERT DE DATOS
SELECT 
    ID_UNIDAD,
    U.NOMBRE, 
    DIRECCION, 
    D.NOMBRE AS DISTRITO,
    U.TIPO
FROM TRX_UNIDADES U INNER JOIN DISTRITOS D
ON U.ID_DISTRITO=D.ID_DISTRITO;

CREATE TABLE dim_aseguradoras (
    id_aseguradora   NUMBER ,
    nombre VARCHAR2(100),
    contacto VARCHAR2(100),
    telefono VARCHAR2(20),
    email VARCHAR2(100),
    direccion VARCHAR2(200)
);

-- INSERT DE DATOS
SELECT
    ID_ASEGURADORA,
    NOMBRE, CONTACTO, TELEFONO, EMAIL, DIRECCION
FROM ASEGURADORAS;

CREATE TABLE dim_servicios(
    id_servicio NUMBER,
    codigo_estandar VARCHAR2(50),
    descripcion VARCHAR2(100),
    tipo_servicio VARCHAR2(100),
    especialidad VARCHAR2(100),
    precio_unitario NUMBER(10, 2)
);

-- INSERT DE DATOS TODO: VER PORQUE NO SALEN TODOS LOS SERVICIOS
SELECT
    S.ID_SERVICIO,
    S.CODIGO_ESTANDAR,
    S.DESCRIPCION,
    TS.NOMBRE AS TIPO_SERVICIO,
    E.NOMBRE AS ESPECIALIDAD,
    S.PRECIO_UNITARIO
FROM TRX_SERVICIOS S INNER JOIN TRX_TIPOS_SERVICIOS TS
ON S.ID_TIPO_SERVICIO=TS.ID_TIPO_SERVICIO INNER JOIN TRX_ESPECIALIDADES E
ON S.ID_ESPECIALIDAD=E.ID_ESPECIALIDAD;


CREATE TABLE dim_seguros(
    id_seguro NUMBER,
    plan VARCHAR2(50),
    aseguradora VARCHAR2(100)
);

-- INSERT DE DATOS
SELECT 
    S.ID_SEGURO,
    S.PLAN,
    A.NOMBRE AS ASEGURADORA
FROM TRX_SEGUROS S INNER JOIN ASEGURADORAS A
ON S.ID_ASEGURADORA=A.ID_ASEGURADORA;


CREATE TABLE dim_tiempo(
    id_tiempo NUMBER,
    fecha DATE,
    mes INT,
    trimestre INT,
    anio INT
);

CREATE TABLE dim_diagnosticos(
    id_diagnostico NUMBER,
    codigo_diagnostico VARCHAR2(20),
    descripcion VARCHAR2(200)
);

CREATE TABLE dim_tipo_urgencia (
    id_tipo_urgencia NUMBER,
    nombre VARCHAR(50),
    descripcion VARCHAR(150),
    nivel_prioridad NUMBER
);

CREATE TABLE fact_consultas_medicas(
    id_atencion NUMBER,
    id_paciente NUMBER,
    id_medico NUMBER,
    id_unidad NUMBER,
    id_servicio NUMBER,
    id_seguro NUMBER,
    id_tiempo NUMBER,
    id_diagnostico NUMBER,
    id_tipo_urgencia NUMBER,
    cobertura_seguro NUMBER(10, 2),
    deducible NUMBER(10, 2),
    costo_total NUMBER(10, 2)
);