SET SERVEROUTPUT ON;

DECLARE
    V_ID_ATENCION NUMBER := 1;
    V_JSON CLOB;
BEGIN
    SELECT JSON_OBJECT(
        'ID_ATENCION' VALUE A.ID_ATENCION,
        'CODIGO_ATENCION' VALUE A.CODIGO_ATENCION,
        'FECHA_ATENCION' VALUE A.FECHA,
        'PACIENTE' VALUE JSON_OBJECT(
            'ID_PACIENTE' VALUE P.ID_PACIENTE,
            'NOMBRE' VALUE P.NOMBRE,
            'EDAD' VALUE P.EDAD,
            'SEXO' VALUE P.SEXO,
            'ZONA' VALUE JSON_OBJECT(
                'DEPARTAMENTO' VALUE DPTO.NOMBRE,
                'MUNICIPIO' VALUE MUNI.NOMBRE,
                'DISTRITO' VALUE DIST.NOMBRE
            )
        ),
        'SERVICIOS' VALUE (
            SELECT JSON_ARRAYAGG(
                JSON_OBJECT(
                    'ID_SERVICIO' VALUE ID_SERVICIO,
                    'DESCRIPCION' VALUE DESCRIPCION,
                    'PRECIO_UNITARIO' VALUE PRECIO_UNITARIO,
                    'CANTIDAD' VALUE CANTIDAD,
                    'COBERTURA' VALUE COBERTURA,
                    'DEDUCIBLE' VALUE DEDUCIBLE,
                    'TOTAL_SERVICIO' VALUE TOTAL_SERVICIO,
                    'MEDICO' VALUE JSON_OBJECT(
                        'ID_MEDICO' VALUE ID_MEDICO,
                        'NOMBRE' VALUE NOMBRE_MEDICO
                    ),
                    'ESPECIALIDAD' VALUE ESPECIALIDAD
                )
            )
            FROM 
            (
                SELECT 
                    S.ID_SERVICIO,
                    S.DESCRIPCION,
                    S.PRECIO_UNITARIO,
                    DET.CANTIDAD,
                    DET.COBERTURA,
                    NVL(MAX(SS.DEDUCIBLE), 0) AS DEDUCIBLE,
                    DET.TOTAL_SERVICIO,
                    M.ID_MEDICO,
                    M.NOMBRE AS NOMBRE_MEDICO,
                    E.NOMBRE AS ESPECIALIDAD
                FROM TRX_DETALLE DET
                JOIN TRX_SERVICIOS S ON DET.ID_SERVICIO = S.ID_SERVICIO
                LEFT JOIN TRX_ESPECIALIDADES E ON S.ID_ESPECIALIDAD = E.ID_ESPECIALIDAD
                JOIN TRX_MEDICOS M ON DET.ID_MEDICO = M.ID_MEDICO
                LEFT JOIN TRX_SEGURO_SERVICIOS SS ON S.ID_SERVICIO = SS.ID_SERVICIO
                WHERE DET.ID_ATENCION = A.ID_ATENCION
                GROUP BY 
                    S.ID_SERVICIO, S.DESCRIPCION, S.PRECIO_UNITARIO,
                    DET.CANTIDAD, DET.COBERTURA, DET.TOTAL_SERVICIO,
                    M.ID_MEDICO, M.NOMBRE, E.NOMBRE
            )
        ),
        'UNIDAD_CLINICA' VALUE JSON_OBJECT(
            'ID_UNIDAD' VALUE U.ID_UNIDAD,
            'NOMBRE' VALUE U.NOMBRE,
            'DIRECCION' VALUE U.DIRECCION,
            'TIPO' VALUE U.TIPO
        ),
        'MONTO_TOTAL' VALUE A.MONTO_TOTAL,
        'MONTO_PAGADO' VALUE A.MONTO_PAGADO,
        'COBERTURA_SEGURO' VALUE (
            SELECT SUM(DET2.COBERTURA)
            FROM TRX_DETALLE DET2
            WHERE DET2.ID_ATENCION = A.ID_ATENCION
        ),
        'FIRMA_DIGITAL' VALUE STANDARD_HASH(
            TO_CHAR(A.ID_ATENCION)
            || TO_CHAR(A.FECHA, 'YYYY-MM-DD HH24:MI:SS')
            || NVL(P.NOMBRE, '')
            || TO_CHAR(A.MONTO_TOTAL, '9999990.99'),
            'SHA256'
        )
    )
    INTO V_JSON
    FROM TRX_ATENCIONES A
    JOIN TRX_PACIENTES P ON A.ID_PACIENTE = P.ID_PACIENTE
    JOIN DISTRITOS DIST ON P.ID_DISTRITO = DIST.ID_DISTRITO
    JOIN MUNICIPIOS MUNI ON DIST.ID_MUNICIPIO = MUNI.ID_MUNICIPIO
    JOIN DEPARTAMENTOS DPTO ON MUNI.ID_DEPARTAMENTO = DPTO.ID_DEPARTAMENTO
    JOIN TRX_UNIDADES U ON A.ID_UNIDAD = U.ID_UNIDAD
    WHERE A.ID_ATENCION = V_ID_ATENCION
    FETCH FIRST 1 ROWS ONLY;

    DBMS_OUTPUT.PUT_LINE(V_JSON);
END;
/


SELECT * FROM TRX_DETALLE WHERE ID_ATENCION = 1;