-- ===========================================================
-- LIMPIEZA DE OBJETOS EXISTENTES (TABLAS, FUNCIONES, VISTAS)
-- ===========================================================
BEGIN
    -- ELIMINAR LAS TABLAS
    FOR t IN (
        SELECT table_name 
        FROM user_tables 
        WHERE table_name IN (
            'TRX_PAGOS',
            'TRX_DETALLE_INSUMOS',
            'TRX_DETALLE',
            'ATENCION_DIAGNOSTICOS',
            'trx_datos_preliminares',
            'TRX_ATENCIONES',
            'TRX_TIPO_URGENCIA',
            'TRX_SEGURO_SERVICIOS',
            'TRX_SERVICIOS',
            'TRX_TIPOS_SERVICIOS',
            'TRX_PACIENTE_SEGUROS',
            'TRX_SEGUROS',
            'ASEGURADORAS',
            'TRX_UNIDADES',
            'TRX_MEDICO_ESPECIALIDADES',
            'TRX_MEDICOS',
            'TRX_ESPECIALIDADES',
            'CONTACTOS_EMERGENCIA',
            'TRX_PACIENTES',
            'TRX_INSUMOS',
            'CIE10_DIAGNOSTICOS',
            'DISTRITOS',
            'MUNICIPIOS',
            'DEPARTAMENTOS'
        )
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;

    -- ELIMINAR FUNCIONES
    FOR f IN (SELECT object_name FROM user_objects WHERE object_type = 'FUNCTION') LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP FUNCTION ' || f.object_name;
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;
END;
/

CREATE OR REPLACE FUNCTION calcular_edad(p_fecha_nacimiento DATE)
RETURN NUMBER
DETERMINISTIC
IS
    v_edad NUMBER;
BEGIN
    -- Calcula edad en años cumplidos
    v_edad := TRUNC(MONTHS_BETWEEN(SYSDATE, p_fecha_nacimiento)/12);
    RETURN v_edad;
END;
/

-- ==========================================
-- TABLAS CATALOGO PARA DIRECCIONES
-- ==========================================

-- DEPARTAMENTOS
CREATE TABLE departamentos (
    id_departamento   NUMBER PRIMARY KEY,
    nombre            VARCHAR2(100) NOT NULL UNIQUE
);

-- MUNICIPIOS
CREATE TABLE municipios (
    id_municipio      NUMBER PRIMARY KEY,
    nombre            VARCHAR2(150) NOT NULL,
    id_departamento   NUMBER NOT NULL,
    CONSTRAINT fk_mun_dep FOREIGN KEY (id_departamento) REFERENCES departamentos(id_departamento)
);

-- DISTRITOS
CREATE TABLE distritos (
    id_distrito       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            VARCHAR2(150) NOT NULL,
    id_municipio      NUMBER NOT NULL,
    CONSTRAINT fk_dis_mun FOREIGN KEY (id_municipio) REFERENCES municipios(id_municipio)
);

-- TABLA DIAGNOSTICOS (CIE-10)
CREATE TABLE cie10_diagnosticos (
    id_diagnostico   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo           VARCHAR2(10) NOT NULL UNIQUE,
    descripcion      VARCHAR2(255) NOT NULL
);

-- INSUMOS MEDICOS (MEDICAMENTOS, MATERIALES, ETC.)
CREATE TABLE trx_insumos (
    id_insumo       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR2(100) NOT NULL,
    descripcion     VARCHAR2(200),
    unidad_medida   VARCHAR2(50), -- caja, frasco, unidad, etc.
    precio_unitario NUMBER(10,2) NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at      TIMESTAMP
);

-- ==========================================
-- CREACION DE TABLAS MESTRAS
-- ==========================================

-- PARA EL REGISTRO DE LOS PACIENTES
CREATE TABLE trx_pacientes (
    id_paciente       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            VARCHAR2(100) NOT NULL,
    sexo              CHAR(1) CHECK (sexo IN ('M','F')),
    fecha_nacimiento  DATE NOT NULL,
    edad              NUMBER AS (calcular_edad(fecha_nacimiento)) VIRTUAL,
    telefono          VARCHAR2(15) NOT NULL,
    email             VARCHAR2(100),
    direccion         VARCHAR2(200) NOT NULL,
    id_distrito       NUMBER NOT NULL,
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at        TIMESTAMP,
    CONSTRAINT fk_pac_distrito FOREIGN KEY (id_distrito) REFERENCES distritos(id_distrito)
);

CREATE TABLE contactos_emergencia (
    id_contacto       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente       NUMBER NOT NULL,
    nombre            VARCHAR2(100) NOT NULL,
    telefono          VARCHAR2(15) NOT NULL,
    relacion          VARCHAR2(50), -- familiar, amigo, etc.
    CONSTRAINT fk_ce_paciente FOREIGN KEY (id_paciente) REFERENCES trx_pacientes(id_paciente)
);

-- ESPECIALIDADES MEDICAS
CREATE TABLE trx_especialidades (
    id_especialidad   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            VARCHAR2(100) NOT NULL UNIQUE,
    descripcion       VARCHAR2(200),
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at        TIMESTAMP
);

-- MEDICOS DISPONIBLES EN EL SISTEMA
CREATE TABLE trx_medicos (
    id_medico          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre             VARCHAR2(100) NOT NULL,
    numero_registro    VARCHAR2(50) UNIQUE,
    direccion          VARCHAR2(200),
    telefono           VARCHAR2(15),
    email              VARCHAR2(100),
    created_at         TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at         TIMESTAMP
);

-- RELACION DE MEDICOS CON SUS ESPECIALIDADES (UN MEDICO PUEDE TENER VARIAS ESPECIALIDADES)
CREATE TABLE trx_medico_especialidades (
    id_medico_especialidad  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_medico               NUMBER NOT NULL,
    id_especialidad         NUMBER NOT NULL,
    CONSTRAINT fk_me_medico FOREIGN KEY (id_medico)       REFERENCES trx_medicos(id_medico),
    CONSTRAINT fk_me_especialidad FOREIGN KEY (id_especialidad) REFERENCES trx_especialidades(id_especialidad)
);

-- CLINICAS O SEDES DONDE SE BRINDAN ATENCIONES
CREATE TABLE trx_unidades (
    id_unidad   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR2(100) NOT NULL,
    direccion   VARCHAR2(200) NOT NULL,
    id_distrito NUMBER NOT NULL,
    tipo        VARCHAR2(50), -- hospital, clínica, consultorio
    latitud     DECIMAL(10,7),
    longitud    DECIMAL(10,7),
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at  TIMESTAMP,
    CONSTRAINT fk_unidad_distrito FOREIGN KEY (id_distrito) REFERENCES distritos(id_distrito)
);

-- INFORMACION DE LAS ASEGURADORAS
CREATE TABLE aseguradoras (
    id_aseguradora   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR2(100) NOT NULL UNIQUE,
    contacto         VARCHAR2(100),
    telefono         VARCHAR2(20),
    email            VARCHAR2(100),
    direccion        VARCHAR2(200),
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at       TIMESTAMP
);

-- PLANES Y COBERTURAS DE SEGUROS
CREATE TABLE trx_seguros (
    id_seguro            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_aseguradora       NUMBER NOT NULL,
    plan                 VARCHAR2(50),
    vigencia_inicio      DATE,
    vigencia_fin         DATE,
    created_at           TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at           TIMESTAMP,
    CONSTRAINT fk_seg_aseguradora FOREIGN KEY (id_aseguradora) REFERENCES aseguradoras(id_aseguradora)
);

-- RELACION DE PACIENTES CON SUS SEGUROS (UN PACIENTE PUEDE TENER VARIOS SEGUROS)
CREATE TABLE trx_paciente_seguros (
    id_paciente_seguro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente  NUMBER NOT NULL,
    id_seguro    NUMBER NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin    DATE,
    numero_poliza VARCHAR2(50),
    estado       VARCHAR2(20) DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO','SUSPENDIDO')),
    CONSTRAINT fk_ps_paciente FOREIGN KEY (id_paciente) REFERENCES trx_pacientes(id_paciente),
    CONSTRAINT fk_ps_seguro   FOREIGN KEY (id_seguro)   REFERENCES trx_seguros(id_seguro)
);

-- TIPOS DE SERVICIOS MEDICOS OFRECIDOS
-- ejemplo: consulta, laboratorio, imagenologia, hospitalizacion, examen, cirugia, terapia, etc.
CREATE TABLE trx_tipos_servicios (
    id_tipo_servicio  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            VARCHAR2(100) NOT NULL UNIQUE,
    descripcion       VARCHAR2(200),
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at        TIMESTAMP
);

-- SERVICIOS MEDICOS OFRECIDOS
CREATE TABLE trx_servicios (
    id_servicio      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_estandar  VARCHAR2(50), -- para normalizar catálogos (Codificacion estandarizada)  // before insert
    descripcion      VARCHAR2(100) NOT NULL,
    id_tipo_servicio NUMBER NOT NULL,
    id_especialidad  NUMBER, -- puede ser null si es un servicio general
    precio_unitario  NUMBER(10,2) NOT NULL,
    vigencia_inicio  DATE NOT NULL,
    vigencia_fin     DATE,
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at       TIMESTAMP,
    CONSTRAINT fk_servicio_tipo FOREIGN KEY (id_tipo_servicio) REFERENCES trx_tipos_servicios(id_tipo_servicio),
    CONSTRAINT fk_servicio_especialidad FOREIGN KEY (id_especialidad) REFERENCES trx_especialidades(id_especialidad)
);

-- RELACION DE SEGUROS CON LOS SERVICIOS QUE CUBREN
CREATE TABLE trx_seguro_servicios (
    id_seguro_servicio NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_seguro     NUMBER NOT NULL,
    id_servicio   NUMBER NOT NULL,
    cobertura_porcentaje NUMBER(5,2),   -- % específico para este servicio
    deducible     NUMBER(10,2),         -- monto a cargo del paciente para este servicio
    copago        NUMBER(10,2),         -- monto a cargo del paciente para este servicio
    cubierto      CHAR(1) DEFAULT 'S' CHECK (cubierto IN ('S','N')),
    CONSTRAINT fk_ss_seguro   FOREIGN KEY (id_seguro)  REFERENCES trx_seguros(id_seguro),
    CONSTRAINT fk_ss_servicio FOREIGN KEY (id_servicio) REFERENCES trx_servicios(id_servicio)
);

CREATE TABLE trx_tipo_urgencia (
    id_tipo_urgencia NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50),
    descripcion VARCHAR2(150),
    nivel_prioridad NUMBER NOT NULL
);

-- ==========================================
-- TABLAS TRANSACCIONALES
-- ==========================================

-- REGISTRO DE ATENCION POR PACIENTE
CREATE TABLE trx_atenciones (
    id_atencion   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha         TIMESTAMP DEFAULT SYSTIMESTAMP,
    id_paciente   NUMBER NOT NULL,
    id_unidad     NUMBER NOT NULL,
    monto_total   NUMBER(12,2),
    monto_pagado  NUMBER(12,2),
    uso_seguro   CHAR(1) DEFAULT 'N' CHECK (uso_seguro IN ('S','N')),
    id_tipo_urgencia NUMBER,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at    TIMESTAMP,
    CONSTRAINT fk_atencion_paciente FOREIGN KEY (id_paciente) REFERENCES trx_pacientes(id_paciente),
    CONSTRAINT fk_atencion_unidad   FOREIGN KEY (id_unidad)   REFERENCES trx_unidades(id_unidad),
    CONSTRAINT fk_atencion_tipo_urgencia FOREIGN KEY (id_tipo_urgencia) REFERENCES trx_tipo_urgencia(id_tipo_urgencia)
);

CREATE TABLE trx_datos_preliminares (
    id_dato_preliminar NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente        NUMBER NOT NULL,
    fecha_registro     TIMESTAMP DEFAULT SYSTIMESTAMP,
    altura_cm          NUMBER(5,2),       -- Altura en centímetros
    peso_lb            NUMBER(5,2),       -- Peso en libras
    temperatura_c      NUMBER(4,1),       -- Temperatura corporal
    presion_sistolica  NUMBER(3),         -- Ej: 120
    presion_diastolica NUMBER(3),         -- Ej: 80
    frecuencia_cardiaca NUMBER(3),        -- Latidos por minuto
    saturacion_o2      NUMBER(3),         -- % de oxigenación
    observaciones      VARCHAR2(255),
    created_at         TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at         TIMESTAMP,
    CONSTRAINT fk_dp_paciente FOREIGN KEY (id_paciente) REFERENCES trx_pacientes(id_paciente)
);

CREATE TABLE atencion_diagnosticos (
    id_atencion    NUMBER NOT NULL,
    id_diagnostico NUMBER NOT NULL,
    diagnostico_principal CHAR(1) DEFAULT 'N' CHECK (diagnostico_principal IN ('S','N')),
    observaciones  VARCHAR2(255),
    CONSTRAINT pk_atencion_diagnosticos PRIMARY KEY (id_atencion, id_diagnostico),
    CONSTRAINT fk_atencion FOREIGN KEY (id_atencion) REFERENCES trx_atenciones(id_atencion),
    CONSTRAINT fk_diagnostico FOREIGN KEY (id_diagnostico) REFERENCES cie10_diagnosticos(id_diagnostico)
);

-- DETALLE DE SERVICIOS PRESTADOS EN CADA ATENCION
CREATE TABLE trx_detalle (
    id_detalle      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_atencion     NUMBER NOT NULL,
    id_servicio     NUMBER NOT NULL,
    id_seguro       NUMBER, -- puede ser null si el paciente no tiene seguro
    id_medico       NUMBER NOT NULL,
    cantidad        NUMBER(5) DEFAULT 1,
    precio_unitario NUMBER(10,2),
    cobertura       NUMBER(10,2), -- cubierto por el seguro (validar si el paciente hace uso del seguro (tabla atenciones uso_seguro))
    --deducible       NUMBER(10,2), -- monto a cargo del paciente
    total_servicio  NUMBER(12,2), -- total a pagar por el servicio (cantidad * precio_unitario)
    observacion     VARCHAR2(200),
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at      TIMESTAMP,
    CONSTRAINT fk_atencion_seguro   FOREIGN KEY (id_seguro)   REFERENCES trx_seguros(id_seguro),
    CONSTRAINT fk_detalle_atencion FOREIGN KEY (id_atencion) REFERENCES trx_atenciones(id_atencion),
    CONSTRAINT fk_detalle_servicio FOREIGN KEY (id_servicio) REFERENCES trx_servicios(id_servicio),
    CONSTRAINT fk_detalle_medico   FOREIGN KEY (id_medico)   REFERENCES trx_medicos(id_medico)
);

-- detalle_insumos: para registrar insumos o medicamentos usados en la atencion
CREATE TABLE trx_detalle_insumos (
    id_detalle_insumo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_detalle        NUMBER NOT NULL,
    id_insumo         NUMBER NOT NULL,
    descripcion       VARCHAR2(100) NOT NULL,
    cantidad          NUMBER(5) DEFAULT 1,
    precio_unitario   NUMBER(10,2),
    total_insumo      NUMBER(12,2), -- total a pagar por el insumo (cantidad * precio_unitario)
    observacion       VARCHAR2(200),
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at        TIMESTAMP,
    CONSTRAINT fk_di_detalle FOREIGN KEY (id_detalle) REFERENCES trx_detalle(id_detalle),
    CONSTRAINT fk_di_insumo  FOREIGN KEY (id_insumo)  REFERENCES trx_insumos(id_insumo)
);

-- REGISTRO DE PAGOS REALIZADOS POR PACIENTES O SEGUROS, 
-- SE PUEDEN HACER VARIOS PAGOS POR ATENCION YA QUE PUEDE PAGAR UNA PARTE EL PACIENTE Y OTRA PARTE EL SEGURO
CREATE TABLE trx_pagos (
    id_pago      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_atencion  NUMBER NOT NULL,
    fecha_pago   TIMESTAMP DEFAULT SYSTIMESTAMP,
    monto        NUMBER(12,2),
    metodo       VARCHAR2(50) CHECK (metodo IN ('EFECTIVO','TARJETA','TRANSFERENCIA','CHEQUE')),
    -- origen_pago  VARCHAR2(20) CHECK (origen_pago IN ('PACIENTE','SEGURO')), -- para saber quien realiza el pago
    observacion  VARCHAR2(200),
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at   TIMESTAMP,
    CONSTRAINT fk_pago_atencion FOREIGN KEY (id_atencion) REFERENCES trx_atenciones(id_atencion)
);
